### ISSUE TITLE
Ideapad 510-15IKB

### ISSUE THREAD

**Issue by trgcyln** [29satnam/LenovoHackintosh#11]
Hello,

i5-7200U
NVIDIA GeForce 940MX
8GB DDR4

Specs are roughly the same same. Can I use this clover ?
Do I need to do dsdt patch ? 
Last question, I'm trying to install Catalina 10.15.3
Did you ever try Catalina ?

Thank you for sharing.

**Comment by 29satnam** [comment]
This repo is only for Ideapad 510-15IKB.
Won't work with yours.
