### ISSUE TITLE
Does this laptop have wifi card whitelist?

### ISSUE THREAD

**Issue by CoCoThink** [29satnam/LenovoHackintosh#5]
Thanks for your work! Does this laptop have a Wifi card whitelist? Do I need to flash bios to replace wifi card?

**Comment by 29satnam** [comment]
DW1560 BCM94352Z NGFF M.2 works OOB.
You don't need to flash BIOS or whitelist.

**Comment by rogerzero** [comment]
Does DW1829A is supported OOB?
Because it has same chip BCM94352Z .
Or, where should i get the whitelisted BIOS?

**Comment by 29satnam** [comment]
I changed the card and it worked, I don't think it has a whitelist. And I never heard of DW1829A.
Best bet is BCM94360NG.

**Comment by rogerzero** [comment]
DW1820A, my bad.
Thanks for your info, i'll tell you when i changed it.

**Comment by 29satnam** [comment]
> DW1820A, my bad.
> Thanks for your info, i'll tell you when i changed it.

DW1820A is nothing but trouble.

**Comment by rogerzero** [comment]
How is that so?
I found some solution https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/

**Comment by 29satnam** [comment]
> How is that so?
> I found some solution https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/

It's very problematic.
