### ISSUE TITLE
Sleep, battery Percentage not working

### ISSUE THREAD

**Issue by ezekiel1998** [29satnam/LenovoHackintosh#6]
My model is Lenovo Ideapad 310-14IKB( Same as yours) using your 10.14.3 EFI Clover, Sleep, battery Percentage not working. After Sleep, laptop will hang on black screen and wait a while got mouse but the laptop will lag. In the Energy Saver Preferences, Current Battery Charges shows 0% and can't show battery status in menu bar. Afters from that seen work perfectly.

**Comment by 29satnam** [comment]
Hey! Battery status is directly related to DSDT, it can differ from system to system cause of different BIOS version. 
- I fixed DSDT for 2 BIOS versions.
For somewhat latest: https://github.com/29satnam/LenovoHackintosh/blob/master/DSDT.aml
Second you will find in this file. https://github.com/29satnam/LenovoHackintosh/blob/master/HighSierra_10.13.3_EFI.zip
I haven't looked into sleep issue, but try some Whatevergreen fixes.

- This might fix your hang after sleep fix, but I'm not certainly sure bout it.
https://www.tonymacx86.com/threads/solved-intel-hd-620-high-sierra-sleep-wake-problem.233174/page-4#post-1637263

**Comment by ezekiel1998** [comment]
tried two dsdt, still doesn't work. ;(

**Comment by ezekiel1998** [comment]
i ard updated my bios to the latest version

**Comment by ezekiel1998** [comment]
![screenshot 2019-03-07 at 12 00 23 am](https://user-images.githubusercontent.com/1438547/53895077-3321a780-406c-11e9-8e93-6e8e5e637330.png)
![screenshot 2019-03-07 at 12 00 37 am](https://user-images.githubusercontent.com/1438547/53895081-35840180-406c-11e9-9fe0-96680223b440.png)

**Comment by 29satnam** [comment]
- Here's DSDT fix for battery:
https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/

- After fix, use this kext:
https://github.com/RehabMan/OS-X-ACPI-Battery-Driver

It always works.

**Comment by ezekiel1998** [comment]
Can I know which patch did u applied for your dsdt?

**Comment by 29satnam** [comment]
Already told you mate.
