### ISSUE TITLE
Does it need a patch again?

### ISSUE THREAD

**Issue by suryol** [29satnam/LenovoHackintosh#7]
Hello @29satnam , thank you for creating a collection of files that can be used to run Hackintosh - macOS 10.14.5 - on this laptop. I have a laptop and specifications that are a bit like you.

My laptop doesn't use BCM94352Z for Wifi and Bluetooth, I use USB Wifi and it runs smoothly using chris1111's [Wireless USB Adapter Clover](https://github.com/chris1111/Wireless-USB-Adapter-Clover) patch. Bluetooth also runs smoothly with the default card.

It does need a little adjustment on your EFI zip, like removing broadcomm kexts to successfully boot without a "stop" when booting the apple logo.

However, there are some patches from your EFI that don't run at all, such as sleep-wake, battery percentage, touchpad gesture, and high brightness on each switch.

To make hackintosh like "native mac" what should I do? Bios that I use the latest 2WCN42WW version from the [web ](https://pcsupport.lenovo.com/id/en/products/laptops-and-netbooks/lenovo-v-series-laptops/v310-14ikb/downloads?linkTrack=&searchType=3&keyWordSearch=V310-14IKB%20Laptop%20(Lenovo))

thank you

**Comment by 29satnam** [comment]
If your laptop model isn’t exactly ‘Lenovo Ideapad 310-14IKB’, you are on your own.
